### ISSUE TITLE
项目deploy的时候失败了

### ISSUE THREAD

**Issue by ysyszrj** [leancloud/LeanEngine-WechatBot#7]
windows系统
看了一下，本地也不能通过，的确是安装了 leanengine的包，只是一直提示init不是function

```
2016-08-06 23:47:13 [ERROR] 实例日志：[ERROR] npm ERR! Linux 3.13.0-92-generic
[ERROR] npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! LeanEngine_Weixin_Sample@1.0.0 start: `node server.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the LeanEngine_Weixin_Sample@1.0.0 start script 'node server.js'.
[ERROR] npm ERR! This is most likely a problem with the LeanEngine_Weixin_Sample package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node server.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs LeanEngine_Weixin_Sample
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!
[ERROR] npm ERR!     npm owner ls LeanEngine_Weixin_Sample
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/leanengine/app/npm-debug.log
[INFO] > LeanEngine_Weixin_Sample@1.0.0 start /home/leanengine/app
[INFO] > node server.js
[ERROR] /home/leanengine/app/server.js:4
[ERROR] AV.init({
[ERROR]    ^
[ERROR] TypeError: undefined is not a function
[ERROR]     at Object.<anonymous> (/home/leanengine/app/server.js:4:4)
[ERROR]     at Module._compile (module.js:460:26)
[ERROR]     at Object.Module._extensions..js (module.js:478:10)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)
[ERROR]     at Function.Module.runMain (module.js:501:10)
[ERROR]     at startup (node.js:129:16)
[ERROR]     at node.js:814:3
[ERROR] npm ERR! Linux 3.13.0-92-generic
[ERROR] npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! LeanEngine_Weixin_Sample@1.0.0 start: `node server.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the LeanEngine_Weixin_Sample@1.0.0 start script 'node server.js'.
[ERROR] npm ERR! This is most likely a problem with the LeanEngine_Weixin_Sample package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node server.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs LeanEngine_Weixin_Sample
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!
[ERROR] npm ERR!     npm owner ls LeanEngine_Weixin_Sample
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/leanengine/app/npm-debug.log
[INFO] > LeanEngine_Weixin_Sample@1.0.0 start /home/leanengine/app
[INFO] > node server.js
[ERROR] /home/leanengine/app/server.js:4
[ERROR] AV.init({
[ERROR]    ^
[ERROR] TypeError: undefined is not a function
[ERROR]     at Object.<anonymous> (/home/leanengine/app/server.js:4:4)
[ERROR]     at Module._compile (module.js:460:26)
[ERROR]     at Object.Module._extensions..js (module.js:478:10)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)
[ERROR]     at Function.Module.runMain (module.js:501:10)
[ERROR]     at startup (node.js:129:16)
[ERROR]     at node.js:814:3
[ERROR] npm ERR! Linux 3.13.0-92-generic
[ERROR] npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! LeanEngine_Weixin_Sample@1.0.0 start: `node server.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the LeanEngine_Weixin_Sample@1.0.0 start script 'node server.js'.
[ERROR] npm ERR! This is most likely a problem with the LeanEngine_Weixin_Sample package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node server.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs LeanEngine_Weixin_Sample
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!
[ERROR] npm ERR!     npm owner ls LeanEngine_Weixin_Sample
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/leanengine/app/npm-debug.log

2016-08-06 23:47:13 [ERROR] 应用启动失败: 无法访问应用的 Web 端口（connect ECONNREFUSED 10.10.135.193:43727），请确保程 序正确启动了 HTTP 服务
2016-08-06 23:47:13 [ERROR] 新建实例已被移除
2016-08-06 23:47:13 [ERROR] 应用启动失败: 无法访问应用的 Web 端口（connect ECONNREFUSED 10.10.135.193:43727），请确保程 序正确启动了 HTTP 服务
2016-08-06 23:47:13 [INFO] 部署完成：发生了 1 个错误
抱歉，部署应用失败：应用启动失败: 无法访问应用的 Web 端口（connect ECONNREFUSED 10.10.135.193:43727），请确保程序正确启 动了 HTTP 服务

```

**Comment by ysyszrj** [comment]
用基于[node-js-getting-started](https://github.com/leancloud/node-js-getting-started)的代码，好像没出错。
